//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiCoffeeShop.MVVM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_TABLE
    {
        public int TB_ID { get; set; }
        public Nullable<int> GT_ID { get; set; }
        public string TB_STATUS { get; set; }
        public Nullable<bool> IS_DELETED { get; set; }
    
        public virtual GENRE_TABLE GENRE_TABLE { get; set; }
    }
}
