//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiCoffeeShop.MVVM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLOYEE()
        {
            this.BILLs = new HashSet<BILL>();
            this.EMPLOYEE_SHIFT = new HashSet<EMPLOYEE_SHIFT>();
            this.EXPORTs = new HashSet<EXPORT>();
            this.IMPORTs = new HashSet<IMPORT>();
            this.REQUESTs = new HashSet<REQUEST>();
        }
    
        public int EMP_ID { get; set; }
        public string EMP_NAME { get; set; }
        public string EMP_PHONE { get; set; }
        public string EMP_CCCD { get; set; }
        public Nullable<System.DateTime> EMP_STARTDATE { get; set; }
        public Nullable<System.DateTime> EMP_BIRTHDAY { get; set; }
        public string EMP_USERNAME { get; set; }
        public string EMP_PASSWORD { get; set; }
        public string EMP_EMAIL { get; set; }
        public string EMP_GENDER { get; set; }
        public string EMP_STATUS { get; set; }
        public Nullable<decimal> EMP_SALARY { get; set; }
        public string EMP_ROLE { get; set; }
        public Nullable<bool> IS_DELETED { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BILL> BILLs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLOYEE_SHIFT> EMPLOYEE_SHIFT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXPORT> EXPORTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMPORT> IMPORTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REQUEST> REQUESTs { get; set; }
    }
}
