//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiCoffeeShop.MVVM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE_SHIFT
    {
        public int EMP_ID { get; set; }
        public int SHIFT_ID { get; set; }
        public byte WORK_DAY { get; set; }
        public Nullable<bool> IS_DELETED { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual WORK_SHIFT WORK_SHIFT { get; set; }
    }
}
