//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiCoffeeShop.MVVM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERROR
    {
        public int ER_ID { get; set; }
        public string ER_NAME { get; set; }
        public string ER_STATUS { get; set; }
        public string ER_DESCRIPTION { get; set; }
        public Nullable<bool> IS_DELETED { get; set; }
    }
}
