//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiCoffeeShop.MVVM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXPORT_INFO
    {
        public int EXP_ID { get; set; }
        public int ING_ID { get; set; }
        public Nullable<int> QUANTITY { get; set; }
        public Nullable<decimal> PRICE_ITEM { get; set; }
        public Nullable<bool> IS_DELETED { get; set; }
    
        public virtual EXPORT EXPORT { get; set; }
        public virtual INGREDIENT INGREDIENT { get; set; }
    }
}
