//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiCoffeeShop.MVVM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMPORT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IMPORT()
        {
            this.IMPORT_INFO = new HashSet<IMPORT_INFO>();
        }
    
        public int IMP_ID { get; set; }
        public Nullable<int> SUP_ID { get; set; }
        public Nullable<int> EMP_ID { get; set; }
        public Nullable<System.DateTime> IMP_DATE { get; set; }
        public Nullable<decimal> TOTAL_COST { get; set; }
        public Nullable<bool> IS_DELETED { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual SUPPLIER SUPPLIER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMPORT_INFO> IMPORT_INFO { get; set; }
    }
}
