//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiCoffeeShop.MVVM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCT()
        {
            this.BILL_INFO = new HashSet<BILL_INFO>();
        }
    
        public int PRO_ID { get; set; }
        public string PRO_NAME { get; set; }
        public Nullable<int> GP_ID { get; set; }
        public string PRO_IMG { get; set; }
        public string PRO_DESCRIPTION { get; set; }
        public Nullable<decimal> PRO_PRICE { get; set; }
        public Nullable<bool> IS_DELETED { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BILL_INFO> BILL_INFO { get; set; }
        public virtual GENRE_PRODUCT GENRE_PRODUCT { get; set; }
    }
}
