//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiCoffeeShop.MVVM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVATION
    {
        public int RES_ID { get; set; }
        public int CUS_ID { get; set; }
        public int TABLE_ID { get; set; }
        public System.DateTime RES_DATE { get; set; }
        public System.DateTime RES_TIME { get; set; }
        public int NUM_OF_PEOPLE { get; set; }
        public string RES_STATUS { get; set; }
        public string SPECIAL_REQUEST { get; set; }
        public Nullable<System.DateTime> CREATE_AT { get; set; }
        public Nullable<bool> IS_DELETED { get; set; }
    
        public virtual C_TABLE C_TABLE { get; set; }
        public virtual CUSTOMER CUSTOMER { get; set; }
    }
}
